export const Categorys = [
  {
    product_id: 1,
    description: "Ropa",
    price: "$ 4990",
    brand_id: "1",
    category_id:"1",
    brand_description: "Zapatos",
    imgs: {
      img1: "/01.jpg",
      img2: "img/shop/categories/02.jpg",
      img3: "img/shop/categories/03.jpg",
      img4: "",
      img5: "",
    },
  },
  {
    product_id: 2,
    description: "Zapatos",
    price: "$ 5625",
    brand_id: "2",
    category_id:"2",
    brand_description: "Zapatos",
    imgs: {
      img1: "img/shop/categories/04.jpg",
      img2: "img/shop/categories/05.jpg",
      img3: "img/shop/categories/06.jpg",
      img4: "",
      img5: "",
    },
  },
  {
    product_id: 3,
    description: "Carteras",
    price: "$ 27.99",
    brand_id: "3",
    category_id:"3",
    brand_description: "Zapatos",
    imgs: {
      img1: "img/shop/categories/07.jpg",
      img2: "img/shop/categories/08.jpg",
      img3: "img/shop/categories/09.jpg",
      img4: "",
      img5: "",
    },
  },
];
